Repository mattermost/mattermost-plugin-splunk, pull requests merged in 2021-12, with the labels that each got.

#51 Add Docker development environment
  build/custom.mk
  dev/Dockerfile
  dev/docker-compose.yml
  dev/splunk_scripts/test_script.sh
  docs/development.md
Labels: 3: QA Review

#56 [issue 54] use postCommandResponse instead of Have bot post ephemeral responses instead of using model.CommandResponse directly
  server/command/command.go
  server/plugin/plugin.go
Labels: 4: Reviews Complete

#57 Allow http as server prefix
  server/command/util.go
  server/command/util_test.go
Labels: 4: Reviews Complete

#58 Fix command ordering
  server/command/command.go
Labels: 2: Dev Review
