Repository mattermost/mattermost-plugin-splunk, pull requests merged in 2023-01, with the labels that each got.

#102 Update docs and Makefile
  docs/development.md
Labels: 2: Dev Review

#101 Fix Login Auth calls
  dev/default.yml
  dev/docker-compose.yml
  docs/development.md
  server/splunk/splunk.go
  server/splunk/splunk_test.go
Labels: 4: Reviews Complete

#86 Improve login flow
  docs/slash-commands.md
  server/command/command.go
  server/splunk/api.go
Labels: 3: QA Review
